using ESG.Application.Common.Interface;
using ESG.Domain.Common;
using ESG.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace ESG.Infrastructure.Persistence
{
    public class ApplicationDbContext : DbContext, IApplicationDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
            _curretDateTime = DateTime.UtcNow;
        }
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<OrganizationUser> OrganizationUsers { get; set; }
        public DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public DbSet<UnitOfMeasureTranslations> UnitOfMeasureTranslations{ get; set; }
        public DbSet<UnitOfMeasureType> UnitOfMeasureTypes { get; set; }
        public DbSet<UnitOfMeasureTypeTranslations> UnitOfMeasureTypeTranslations { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<DimensionType> DimensionTypes { get; set; }
        public DbSet<ESG.Domain.Entities.Dimensions> Dimensions { get; set; }
        public DbSet<DataPointTypes> DataPointTypes { get; set; }
        public DbSet<DatapointTypeTranslations> DatapointTypeTranslations { get; set; }
        public DbSet<DataPointValues> DataPointValues { get; set; }
        public DbSet<DatapointValueTranslations> DatapointValueTranslations { get; set; }
        public DbSet<DimensionTypeTranslations> DimensionTypeTranslations { get; set; }
        public DbSet<DimensionTranslations> DimensionTranslations { get; set; }
        public DbSet<Audit> AuditLogs { get; set; }
        public DateTime _curretDateTime { get; set; }

        public async Task<int> SaveChangesAsync()
        {

            try
            {
                var auditEntries = OnBeforeSaveChanges();
                var result = await base.SaveChangesAsync();
                await OnAfterSaveChanges(auditEntries);
                return result;
            }
            catch (DbUpdateException ex)
            {
                // Log the exception or inspect the inner exception
                Console.WriteLine(ex.InnerException?.Message);
                throw;
            }
        }
        public virtual new DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            return base.Set<TEntity>();
        }
        private List<AuditEntry> OnBeforeSaveChanges()
        {


            foreach (var entity in ChangeTracker.Entries<IAuditableEntity>())
            {
                switch (entity.State)
                {
                    case EntityState.Added:
                        //entity.Entity.CreatedBy = 1;//GetCurrentUser
                        entity.Entity.CreatedDate = _curretDateTime;
                        entity.Entity.LastModifiedBy = 1;
                        entity.Entity.LastModifiedDate = _curretDateTime;
                        break;
                    case EntityState.Modified:
                        entity.Entity.LastModifiedBy = 1;
                        entity.Entity.LastModifiedDate = _curretDateTime;
                        break;
                }
            }


            ChangeTracker.DetectChanges();
            var auditEntries = new List<AuditEntry>();
            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.Entity is Audit || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                    continue;
                var auditEntry = new AuditEntry(entry);
                auditEntry.TableName = entry.Entity.GetType().Name;
                auditEntry.CreatedBy = 1;//GetCurrentUser

                auditEntries.Add(auditEntry);
                foreach (var property in entry.Properties)
                {
                    if (property.IsTemporary)
                    {
                        // value will be generated by the database, get the value after saving
                        auditEntry.TemporaryProperties.Add(property);
                        continue;
                    }
                    string propertyName = property.Metadata.Name;
                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            auditEntry.AuditType = AuditType.Create;
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                            break;

                        case EntityState.Deleted:
                            auditEntry.AuditType = AuditType.Delete;
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            break;

                        case EntityState.Modified:
                            if (property.IsModified)
                            {
                                auditEntry.ChangedColumns.Add(propertyName);
                                auditEntry.AuditType = AuditType.Update;
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;
                    }
                }
            }
            foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
            {
                AuditLogs.Add(auditEntry.ToAudit());
            }
            return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
        }
        private Task OnAfterSaveChanges(List<AuditEntry> auditEntries)
        {
            if (auditEntries == null || auditEntries.Count == 0)
                return Task.CompletedTask;

            foreach (var auditEntry in auditEntries)
            {
                // Get the final value of the temporary properties
                foreach (var prop in auditEntry.TemporaryProperties)
                {
                    if (prop.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                    else
                    {
                        auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                    }
                }

                // Save the Audit entry
                AuditLogs.Add(auditEntry.ToAudit());
            }

            return SaveChangesAsync();
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(ApplicationDbContext).Assembly);
            modelBuilder.Entity<Language>().HasData(
                new Language { Id = 1, Name = "English", IsoCode = "en" },
                new Language { Id = 2, Name = "French", IsoCode = "fr" },
                new Language { Id = 3, Name = "Belarusian", IsoCode = "be" },
                new Language { Id = 4, Name = "Estonian", IsoCode = "et" },
                new Language { Id = 5, Name = "Latvian", IsoCode = "lv" },
                new Language { Id = 6, Name = "Lithuanian", IsoCode = "lt" },
                new Language { Id = 7, Name = "Georgian", IsoCode = "ka" },
                new Language { Id = 8, Name = "Armenian", IsoCode = "hy" },
                new Language { Id = 9, Name = "Azerbaijani", IsoCode = "az" },
                new Language { Id = 10, Name = "Kazakh", IsoCode = "kk" },
                new Language { Id = 11, Name = "Uzbek", IsoCode = "uz" },
                new Language { Id = 12, Name = "Turkmen", IsoCode = "tk" },
                new Language { Id = 13, Name = "Tajik", IsoCode = "tg" },
                new Language { Id = 14, Name = "Kyrgyz", IsoCode = "ky" },
                new Language { Id = 15, Name = "Moldovan", IsoCode = "mo" },
                new Language { Id = 16, Name = "Tatar", IsoCode = "tt" },
                new Language { Id = 17, Name = "Bashkir", IsoCode = "ba" });

            modelBuilder.Entity<Currency>().HasData(
                new Currency { Id = 1, Name = "US Dollar", CurrencyCode = "USD", ShortText = "USD", LongText = "United States Dollar" },
                new Currency { Id = 2, Name = "Euro", CurrencyCode = "EUR", ShortText = "EUR", LongText = "Euro" },
                new Currency { Id = 3, Name = "Indian Rupee", CurrencyCode = "INR", ShortText = "INR", LongText = "Indian Rupee" },
                new Currency { Id = 4, Name = "British Pound", CurrencyCode = "GBP", ShortText = "GBP", LongText = "British Pound Sterling" },
                new Currency { Id = 5, Name = "Canadian Dollar", CurrencyCode = "CAD", ShortText = "CAD", LongText = "Canadian Dollar" },
                new Currency { Id = 6, Name = "Australian Dollar", CurrencyCode = "AUD", ShortText = "AUD", LongText = "Australian Dollar" },
                new Currency { Id = 7, Name = "Japanese Yen", CurrencyCode = "JPY", ShortText = "JPY", LongText = "Japanese Yen" },
                new Currency { Id = 8, Name = "Swiss Franc", CurrencyCode = "CHF", ShortText = "CHF", LongText = "Swiss Franc" },
                new Currency { Id = 9, Name = "Chinese Yuan", CurrencyCode = "CNY", ShortText = "CNY", LongText = "Chinese Yuan Renminbi" },
                new Currency { Id = 10, Name = "Russian Ruble", CurrencyCode = "RUB", ShortText = "RUB", LongText = "Russian Ruble" }
               );
            modelBuilder.Entity<Tenant>().HasData(
            new Tenant { Id = 1, Name = "ESG Global" });

            modelBuilder.Entity<Organization>().HasData(
                   new Organization
                   {
                       Id = 1,
                       Name = "ESG Global",
                       RegistrationId = "REG-001",
                       FirstName = "John",
                       LatsName = "Doe",
                       StreetAddress = "123 Main St",
                       StreetNumber = "456",
                       PostalCode = "12345",
                       Country = "USA",
                       Email = "john.doe@org1.com",
                       TenantId = 1,
                       LanguageId = 1
                   });
                        modelBuilder.Entity<User>().HasData(
                new User
                {
                    Id = 1,
                    Password = Encoding.UTF8.GetBytes("password1"),
                    SecurityStamp = Guid.NewGuid(),
                    Email = "user1@example.com",
                    FirstName = "John",
                    LastName = "Doe",
                    LanguageId = 1,
                    PhoneNumber = "1234567890",
                    CreatedBy = 1,
                    CreatedDate = DateTime.UtcNow
                },
                new User
                {
                    Id = 2,
                    Password = Encoding.UTF8.GetBytes("password2"),
                    SecurityStamp = Guid.NewGuid(),
                    Email = "user2@example.com",
                    FirstName = "Jane",
                    LastName = "Smith",
                    LanguageId = 1,
                    PhoneNumber = "0987654321",
                    CreatedBy = 1,
                    CreatedDate = DateTime.UtcNow
                },
                new User
                {
                    Id = 3,
                    Password = Encoding.UTF8.GetBytes("password3"),
                    SecurityStamp = Guid.NewGuid(),
                    Email = "user3@example.com",
                    FirstName = "Alice",
                    LastName = "Johnson",
                    LanguageId = 1,
                    PhoneNumber = "2345678901",
                    CreatedBy = 1,
                    CreatedDate = DateTime.UtcNow
                });
            modelBuilder.Entity<Role>().HasData(
                new Role { Id = 1, Name = "AdminEE" },
                new Role { Id = 2, Name = "ClientAdmin" },
                new Role { Id = 3, Name = "User" });

            modelBuilder.Entity<OrganizationUser>().HasData(
               new OrganizationUser { Id = 1, OrganizationId = 1, UserId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
               new OrganizationUser { Id = 2, OrganizationId = 1, UserId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
               new OrganizationUser { Id = 3, OrganizationId = 1, UserId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
               );
            modelBuilder.Entity<UserRole>().HasData(
                 new UserRole { Id = 1, RoleId = 1, UserId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                 new UserRole { Id = 2, RoleId = 2, UserId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                 new UserRole { Id = 3, RoleId = 3, UserId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
                  );

            modelBuilder.Entity<UnitOfMeasureType>().HasData(
                 new UnitOfMeasureType { Id = 1, Code = "speed", Name = "Speed", ShortText = "T1", LongText = "Type 1", OrganizationId = 1, State = StateEnum.active, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1, LanguageId = 1 },
                 new UnitOfMeasureType { Id = 2, Code = "weight", Name = "Weight", ShortText = "T2", LongText = "Type 2", OrganizationId = 1, State = StateEnum.active, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1, LanguageId = 1 },
                 new UnitOfMeasureType { Id = 3, Code = "amount", Name = "Amount", ShortText = "T3", LongText = "Type 3", OrganizationId = 1, State = StateEnum.active, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1, LanguageId = 1 });

            modelBuilder.Entity<UnitOfMeasure>().HasData(
                new UnitOfMeasure { Id = 4, Name = "weight", Code = "weight", ShortText = "kg", LongText = "Kilogram", UnitOfMeasureTypeId = 2, LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasure { Id = 5, Name = "weight", Code = "weight", ShortText = "gm", LongText = "Gram", UnitOfMeasureTypeId = 2, LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasure { Id = 6, Name = "amount", Code = "weight", ShortText = "ml", LongText = "milliliter", UnitOfMeasureTypeId = 3, LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasure { Id = 7, Name = "speed", Code = "weight", ShortText = "m/s", LongText = "meterpersecond", UnitOfMeasureTypeId = 1, LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasure { Id = 8, Name = "speed", Code = "weight", ShortText = "kmph", LongText = "kmperhour", UnitOfMeasureTypeId = 1, LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 });

            modelBuilder.Entity<UnitOfMeasureTranslations>().HasData(
               new UnitOfMeasureTranslations { Id = 10, Name = "weight", ShortText = "kg", LongText = "Kilogram", UnitOfMeasureId = 4, LanguageId = 1,  CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
               new UnitOfMeasureTranslations { Id = 11, Name = "weight",  ShortText = "gm", LongText = "Gram", UnitOfMeasureId = 4, LanguageId = 2,  CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
               new UnitOfMeasureTranslations { Id = 12, Name = "amount",  ShortText = "ml", LongText = "milliliter", UnitOfMeasureId = 6, LanguageId = 1,  CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
               new UnitOfMeasureTranslations { Id = 13, Name = "speed",  ShortText = "m/s", LongText = "meterpersecond", UnitOfMeasureId = 7, LanguageId = 1,  CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
               new UnitOfMeasureTranslations { Id = 14, Name = "speed",  ShortText = "kmph", LongText = "kmperhour", UnitOfMeasureId = 7, LanguageId = 2,  CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 });

            modelBuilder.Entity<UnitOfMeasureTypeTranslations>().HasData(
                new UnitOfMeasureTypeTranslations { Id = 10, Name = "weight", ShortText = "kg", LongText = "Kilogram", UnitOfMeasureTypeId = 2, LanguageId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasureTypeTranslations { Id = 11, Name = "weight", ShortText = "gm", LongText = "Gram", UnitOfMeasureTypeId = 2, LanguageId = 2, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasureTypeTranslations { Id = 12, Name = "amount", ShortText = "ml", LongText = "milliliter", UnitOfMeasureTypeId = 3, LanguageId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasureTypeTranslations { Id = 13, Name = "speed", ShortText = "m/s", LongText = "meterpersecond", UnitOfMeasureTypeId = 1, LanguageId = 1, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 },
                new UnitOfMeasureTypeTranslations { Id = 14, Name = "speed", ShortText = "kmph", LongText = "kmperhour", UnitOfMeasureTypeId = 1, LanguageId = 2, CreatedDate = DateTime.UtcNow, CreatedBy = 1, LastModifiedDate = DateTime.UtcNow, LastModifiedBy = 1 });

            modelBuilder.Entity<DimensionType>().HasData(
                new DimensionType { Id = 1, Name = "ESG Topic", Code = "esg_topic", ShortText = "DimensionType topic", LongText = "Dimension Type 1", LanguageId = 1, isHierarchical = true, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionType { Id = 2, Name = "ESG Standard", Code = "esg-standard", ShortText = "dimensiontype standard", LongText = "Dimension Type 2", LanguageId = 1, isHierarchical = true, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionType { Id = 3, Name = "ESG Disclosure Requirements", Code = "esg-dq", ShortText = "dimensiontype disclosure requirement", LongText = "Dimension Type 3", LanguageId = 1, isHierarchical = true, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
            );
            modelBuilder.Entity<DimensionTypeTranslations>().HasData(
                new DimensionTypeTranslations { Id = 1, Name = "ESG Topic", ShortText = "DimensionType topic", LongText = "Dimension Type 1", DimensionTypeId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionTypeTranslations { Id = 2, Name = "Sujet ESG", ShortText = "Sujet de type de dimension", LongText = "Type de dimension 1", DimensionTypeId = 1, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionTypeTranslations { Id = 3, Name = "ESG Standard", ShortText = "DimensionType standard", LongText = "Dimension Type 2", DimensionTypeId = 2, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionTypeTranslations { Id = 4, Name = "Norme ESG", ShortText = "Norme de type de dimension", LongText = "Type de dimension 2", DimensionTypeId = 2, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionTypeTranslations { Id = 5, Name = "ESG Disclosure Requirements", ShortText = "DimensionType disclosure requirement", LongText = "Dimension Type 3", DimensionTypeId = 3, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
                new DimensionTypeTranslations { Id = 6, Name = "Exigences de divulgation ESG", ShortText = "Exigences de divulgation de type de dimension", LongText = "Type de dimension 3", DimensionTypeId = 3, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
            );
            modelBuilder.Entity<Dimensions>().HasData(
                new Dimensions { Id = 100, Code = "general", Name = "general", ShortText = "general", LongText = "general", LanguageId = 1, DimensionTypeId = 1, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 101, Code = "environment", Name = "environment", ShortText = "environment", LongText = "environment", LanguageId = 1, DimensionTypeId = 1, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 102, Code = "social", Name = "social", ShortText = "social", LongText = "social", LanguageId = 1, DimensionTypeId = 1, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 103, Code = "governance", Name = "governance", ShortText = "governance", LongText = "governance", LanguageId = 1, DimensionTypeId = 1, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 104, Code = "ESRS2_GP", Name = "ESRS2_GP", ShortText = "General principles", LongText = "General principles", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 105, Code = "ESRS2_MDR", Name = "ESRS2_MDR", ShortText = "General disclosures", LongText = "General disclosures", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 106, Code = "E1", Name = "E1", ShortText = "Climate change", LongText = "Climate change", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 107, Code = "E2", Name = "E2", ShortText = "Pollution", LongText = "Pollution", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 108, Code = "E3", Name = "E3", ShortText = "Water & marine resources", LongText = "Water & marine resources", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 109, Code = "E4", Name = "E4", ShortText = "Biodiversity and eco systems", LongText = "Biodiversity and eco systems", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 110, Code = "E5", Name = "E5", ShortText = "Resourtce use and circular economy", LongText = "Resourtce use and circular economy", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 111, Code = "S1", Name = "s1", ShortText = "Own workforce", LongText = "Own workforce", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 112, Code = "S2", Name = "s2", ShortText = "Workers in value chain", LongText = "Workers in value chain", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 113, Code = "S3", Name = "s3", ShortText = "Affected communities", LongText = "Affected communities", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 114, Code = "S4", Name = "s4", ShortText = "Consumers and end-users", LongText = "Consumers and end-users", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 115, Code = "G1", Name = "G1", ShortText = "Business Conduct", LongText = "Business Conduct", LanguageId = 1, DimensionTypeId = 2, isHierarchical = true, OrganizationId = 1 },
                new Dimensions { Id = 116, Code = "BP-1", Name = "BP-1", ShortText = "General basis for preparation of sustainability statements", LongText = "General basis for preparation of sustainability statements", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 117, Code = "BP-2", Name = "BP-2", ShortText = "Disclosures in relation to specific circumstances", LongText = "Disclosures in relation to specific circumstances", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 118, Code = "GOV-1", Name = "GOV-1", ShortText = "The role of the administrative, management and supervisory bodies", LongText = "The role of the administrative, management and supervisory bodies", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 119, Code = "GOV-2", Name = "GOV-2", ShortText = "Information provided to and sustainability matters addressed by the undertaking’s administrative, management and supervisory bodies", LongText = "Information provided to and sustainability matters addressed by the undertaking’s administrative, management and supervisory bodies", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 120, Code = "GOV-3", Name = "GOV-3", ShortText = "Integration of sustainability-related performance in incentive schemes", LongText = "Integration of sustainability-related performance in incentive schemes", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 121, Code = "GOV-4", Name = "GOV-4", ShortText = "Statement on due diligence", LongText = "Statement on due diligence", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 122, Code = "GOV-5", Name = "GOV-5", ShortText = "Risk management and internal controls over sustainability reporting", LongText = "Risk management and internal controls over sustainability reporting", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 123, Code = "SBM-1", Name = "SBM-1", ShortText = "Strategy, business model and value chain", LongText = "Strategy, business model and value chain", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 124, Code = "SBM-2", Name = "SBM-2", ShortText = "Interests and views of stakeholders", LongText = "Interests and views of stakeholders", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 125, Code = "SBM-3", Name = "SBM-3", ShortText = "Material impacts, risks and opportunities and their interaction with strategy and business model", LongText = "Material impacts, risks and opportunities and their interaction with strategy and business model", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 126, Code = "IRO-1", Name = "IRO-1", ShortText = "Description of the process to identify and assess material impacts, risks and opportunities", LongText = "Description of the process to identify and assess material impacts, risks and opportunities", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 127, Code = "IRO-2", Name = "IRO-2", ShortText = "Disclosure requirements in ESRS covered by the undertaking’s sustainability statement", LongText = "Disclosure requirements in ESRS covered by the undertaking’s sustainability statement", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 128, Code = "IRO-3", Name = "IRO-3", ShortText = "Material impacts, risks and opportunities and their interaction with strategy and business model", LongText = "Material impacts, risks and opportunities and their interaction with strategy and business model", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 },
                new Dimensions { Id = 129, Code = "IRO-4", Name = "IRO-4", ShortText = "Material impacts, risks and opportunities in the undertaking’s own operations and value chain", LongText = "Material impacts, risks and opportunities in the undertaking’s own operations and value chain", LanguageId = 1, DimensionTypeId = 3, isHierarchical = false, OrganizationId = 1 }
            );
            modelBuilder.Entity<DimensionTranslations>().HasData(
         new DimensionTranslations { Id = 1, Name = "general", ShortText = "General", LongText = "General", DimensionsId = 100, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 2, Name = "environment", ShortText = "Environment", LongText = "Environment", DimensionsId = 101, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 3, Name = "social", ShortText = "Social", LongText = "Social", DimensionsId = 102, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 4, Name = "governance", ShortText = "Governance", LongText = "Governance", DimensionsId = 103, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 5, Name = "general", ShortText = "Généralités", LongText = "Généralités", DimensionsId = 100, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 6, Name = "environment", ShortText = "Environnement", LongText = "Environnement", DimensionsId = 101, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 7, Name = "social", ShortText = "Social", LongText = "Social", DimensionsId = 102, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 8, Name = "governance", ShortText = "Gouvernance", LongText = "Gouvernance", DimensionsId = 103, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 9, Name = "ESRS2_GP", ShortText = "General principles", LongText = "General principles", DimensionsId = 104, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 10, Name = "ESRS2_MDR", ShortText = "General disclosures", LongText = "General disclosures", DimensionsId = 105, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 11, Name = "E1", ShortText = "Climate change", LongText = "Climate change", DimensionsId = 106, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 12, Name = "E2", ShortText = "Pollution", LongText = "Pollution", DimensionsId = 107, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 13, Name = "E3", ShortText = "Water & marine resources", LongText = "Water & marine resources", DimensionsId = 108, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 14, Name = "E4", ShortText = "Biodiversity and eco systems", LongText = "Biodiversity and eco systems", DimensionsId = 109, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 15, Name = "E5", ShortText = "Resource use and circular economy", LongText = "Resource use and circular economy", DimensionsId = 110, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 16, Name = "S1", ShortText = "Own workforce", LongText = "Own workforce", DimensionsId = 111, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 17, Name = "S2", ShortText = "Workers in value chain", LongText = "Workers in value chain", DimensionsId = 112, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 18, Name = "S3", ShortText = "Affected communities", LongText = "Affected communities", DimensionsId = 113, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 19, Name = "S4", ShortText = "Consumers and end-users", LongText = "Consumers and end-users", DimensionsId = 114, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 20, Name = "G1", ShortText = "Business Conduct", LongText = "Business Conduct", DimensionsId = 115, LanguageId = 1, CreatedBy = 1 },
         new DimensionTranslations { Id = 21, Name = "ESRS2_GP", ShortText = "Principes généraux", LongText = "Principes généraux", DimensionsId = 104, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 22, Name = "ESRS2_MDR", ShortText = "Informations générales", LongText = "Informations générales", DimensionsId = 105, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 23, Name = "E1", ShortText = "Changement climatique", LongText = "Changement climatique", DimensionsId = 106, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 24, Name = "E2", ShortText = "Pollution", LongText = "Pollution", DimensionsId = 107, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 25, Name = "E3", ShortText = "Ressources en eau et marines", LongText = "Ressources en eau et marines", DimensionsId = 108, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 26, Name = "E4", ShortText = "Biodiversité et écosystèmes", LongText = "Biodiversité et écosystèmes", DimensionsId = 109, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 27, Name = "E5", ShortText = "Utilisation des ressources et économie circulaire", LongText = "Utilisation des ressources et économie circulaire", DimensionsId = 110, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 28, Name = "S1", ShortText = "Main-d'œuvre propre", LongText = "Main-d'œuvre propre", DimensionsId = 111, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 29, Name = "S2", ShortText = "Travailleurs dans la chaîne de valeur", LongText = "Travailleurs dans la chaîne de valeur", DimensionsId = 112, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 30, Name = "S3", ShortText = "Communautés affectées", LongText = "Communautés affectées", DimensionsId = 113, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 31, Name = "S4", ShortText = "Consommateurs et utilisateurs finaux", LongText = "Consommateurs et utilisateurs finaux", DimensionsId = 114, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 32, Name = "G1", ShortText = "Conduite des affaires", LongText = "Conduite des affaires", DimensionsId = 115, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 33, Name = "BP-1", ShortText = "Base générale pour la préparation des déclarations de durabilité", LongText = "Base générale pour la préparation des déclarations de durabilité", DimensionsId = 116, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 34, Name = "BP-2", ShortText = "Divulgations concernant des circonstances spécifiques", LongText = "Divulgations concernant des circonstances spécifiques", DimensionsId = 117, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 35, Name = "GOV-1", ShortText = "Le rôle des organes administratifs, de gestion et de surveillance", LongText = "Le rôle des organes administratifs, de gestion et de surveillance", DimensionsId = 118, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 36, Name = "GOV-2", ShortText = "Informations fournies et questions de durabilité traitées par les organes administratifs, de gestion et de surveillance de l’entreprise", LongText = "Informations fournies et questions de durabilité traitées par les organes administratifs, de gestion et de surveillance de l’entreprise", DimensionsId = 119, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 37, Name = "GOV-3", ShortText = "Intégration de la performance liée à la durabilité dans les systèmes de rémunération", LongText = "Intégration de la performance liée à la durabilité dans les systèmes de rémunération", DimensionsId = 120, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 38, Name = "GOV-4", ShortText = "Déclaration sur la diligence raisonnable", LongText = "Déclaration sur la diligence raisonnable", DimensionsId = 121, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 39, Name = "GOV-5", ShortText = "Gestion des risques et contrôles internes sur la déclaration de durabilité", LongText = "Gestion des risques et contrôles internes sur la déclaration de durabilité", DimensionsId = 122, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 40, Name = "SBM-1", ShortText = "Stratégie, modèle économique et chaîne de valeur", LongText = "Stratégie, modèle économique et chaîne de valeur", DimensionsId = 123, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 41, Name = "SBM-2", ShortText = "Intérêts et points de vue des parties prenantes", LongText = "Intérêts et points de vue des parties prenantes", DimensionsId = 124, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 42, Name = "SBM-3", ShortText = "Impacts matériels, risques et opportunités et leur interaction avec la stratégie et le modèle économique", LongText = "Impacts matériels, risques et opportunités et leur interaction avec la stratégie et le modèle économique", DimensionsId = 125, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 43, Name = "IRO-1", ShortText = "Description du processus pour identifier et évaluer les impacts matériels, risques et opportunités", LongText = "Description du processus pour identifier et évaluer les impacts matériels, risques et opportunités", DimensionsId = 126, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 44, Name = "IRO-2", ShortText = "Exigences de divulgation dans les ESRS couvertes par la déclaration de durabilité de l’entreprise", LongText = "Exigences de divulgation dans les ESRS couvertes par la déclaration de durabilité de l’entreprise", DimensionsId = 127, LanguageId = 2, CreatedBy = 1 },
         new DimensionTranslations { Id = 45, Name = "IRO-3", ShortText = "Impacts matériels, risques et opportunités et leur interaction avec la stratégie et le modèle économique", LongText = "Impacts matériels, risques et opportunités et leur interaction avec la stratégie et le modèle économique", DimensionsId = 128, LanguageId = 2, CreatedBy = 1 });




             //            modelBuilder.Entity<DataPointTypes>().HasData(
             //    new DataPointTypes { Id = 99, Name = "DatapointType1", ShortText = "T1", LongText = "Type 1", LanguageId = 1, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 98, Name = "DatapointType2", ShortText = "T2", LongText = "Type 2", LanguageId = 1, OrganizationId = 1, CreatedBy = 2, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 97, Name = "DatapointType3", ShortText = "T3", LongText = "Type 3", LanguageId = 1, OrganizationId = 1, CreatedBy = 3, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 96, Name = "DatapointType5", ShortText = "T5", LongText = "Type 5", LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 95, Name = "DatapointType6", ShortText = "T6", LongText = "Type 6", LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 94, Name = "DatapointType7", ShortText = "T7", LongText = "Type 7", LanguageId = 1, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 93, Name = "DatapointType8", ShortText = "T8", LongText = "Type 8", LanguageId = 1, OrganizationId = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 92, Name = "DatapointType9", ShortText = "T9", LongText = "Type 9", LanguageId = 1, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointTypes { Id = 91, Name = "DatapointType10", ShortText = "T10", LongText = "Type 10", LanguageId = 1, OrganizationId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
             //);
             //            modelBuilder.Entity<DatapointTypeTranslations>().HasData(
             //    new DatapointTypeTranslations { Id = 101, Name = "DatapointType1", ShortText = "T1", LongText = "Type 1", DatapointTypeId = 99, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DatapointTypeTranslations { Id = 102, Name = "DatapointType1", ShortText = "T2", LongText = "Type 2", DatapointTypeId = 99, LanguageId = 2, CreatedBy = 2, CreatedDate = DateTime.UtcNow },
             //    new DatapointTypeTranslations { Id = 103, Name = "DatapointType2", ShortText = "T3", LongText = "Type 3", DatapointTypeId = 99, LanguageId = 3, CreatedBy = 3, CreatedDate = DateTime.UtcNow }
             //    //new DatapointTypeTranslations { Id = 104, Name = "DatapointType2", ShortText = "T5", LongText = "Type 5", DatapointTypeId = 98, LanguageId = 1, CreatedDate = DateTime.UtcNow },
             //    //new DatapointTypeTranslations { Id = 105, Name = "DatapointType3", ShortText = "T6", LongText = "Type 6", DatapointTypeId = 98, LanguageId = 2, CreatedDate = DateTime.UtcNow },
             //    //new DatapointTypeTranslations { Id = 106, Name = "DatapointType3", ShortText = "T7", LongText = "Type 7", DatapointTypeId = 97,LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    //new DatapointTypeTranslations { Id = 107, Name = "DatapointType5", ShortText = "T8", LongText = "Type 8", DatapointTypeId = 96, LanguageId = 1, CreatedDate = DateTime.UtcNow },
             //    //new DatapointTypeTranslations { Id = 108, Name = "DatapointType5", ShortText = "T9", LongText = "Type 9", DatapointTypeId = 96, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
             //);

             //            modelBuilder.Entity<DataPointValues>().HasData(
             //    new DataPointValues { Id = 1, Name = "DataPointValue1", DatapointTypeId = 99, UnitOfMeasureTypeId = false, IsCurrency = true, IsNarrative = false, OrganizationId = 1, Value = "Value 1", Purpose = "Purpose 1", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 2, Name = "DataPointValue2", DatapointTypeId = 99, UnitOfMeasureTypeId = true, IsCurrency = false, IsNarrative = false, OrganizationId = 1, Value = "Value 2", Purpose = "Purpose 2", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 3, Name = "DataPointValue3", DatapointTypeId = 99, IsUnitOfMeasureTypeIdUOM = false, IsCurrency = true, IsNarrative = false, OrganizationId = 1, Value = "Value 3", Purpose = "Purpose 3", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 4, Name = "DataPointValue4", DatapointTypeId = 98, IsUOM = false, IsCurrency = false, IsNarrative = true, OrganizationId = 1, Value = "Value 4", Purpose = "Purpose 4", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 5, Name = "DataPointValue5", DatapointTypeId = 98, IsUOM = false, IsCurrency = true, IsNarrative = false, OrganizationId = 1, Value = "Value 5", Purpose = "Purpose 5", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 6, Name = "DataPointValue6", DatapointTypeId = 97, IsUOM = true, IsCurrency = false, IsNarrative = false, OrganizationId = 1, Value = "Value 6", Purpose = "Purpose 6", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 7, Name = "DataPointValue7", DatapointTypeId = 97, IsUOM = false, IsCurrency = true, IsNarrative = false, OrganizationId = 1, Value = "Value 7", Purpose = "Purpose 7", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 8, Name = "DataPointValue8", DatapointTypeId = 97, IsUOM = false, IsCurrency = false, IsNarrative = true, OrganizationId = 1, Value = "Value 8", Purpose = "Purpose 8", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 9, Name = "DataPointValue9", DatapointTypeId = 95, IsUOM = false, IsCurrency = true, IsNarrative = false, OrganizationId = 1, Value = "Value 9", Purpose = "Purpose 9", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DataPointValues { Id = 10, Name = "DataPointValue10", DatapointTypeId = 95, IsUOM = true, IsCurrency = false, IsNarrative = false, OrganizationId = 1, Value = "Value 10", Purpose = "Purpose 10", LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
             //);
             //            modelBuilder.Entity<DatapointValueTranslations>().HasData(
             //    new DatapointValueTranslations { Id = 101, Name = "DataPointValue1", DatapointValueId = 1, LanguageId = 1,Value = "10m",Purpose = "--", CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 102, Name = "DataPointValue1", DatapointValueId = 1, LanguageId = 2, Value = "10", Purpose = "--", CreatedBy = 2, CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 103, Name = "DataPointValue2", DatapointValueId = 2, LanguageId = 1, Value = "10", Purpose = "--", CreatedBy = 3, CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 104, Name = "DataPointValue2", DatapointValueId = 2, LanguageId = 2, Value = "10", Purpose = "--", CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 105, Name = "DataPointValue3", DatapointValueId = 3, LanguageId = 1, Value = "10", Purpose = "--", CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 106, Name = "DataPointValue3", DatapointValueId = 3, LanguageId = 2, Value = "10", Purpose = "--", CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 107, Name = "DataPointValue5", DatapointValueId = 5, LanguageId = 1, Value = "10", Purpose = "--", CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 108, Name = "DataPointValue5", DatapointValueId = 5, LanguageId = 2, Value = "10", Purpose = "--", CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DatapointValueTranslations { Id = 109, Name = "DataPointValue5", DatapointValueId = 5, LanguageId = 3, Value = "10", Purpose = "--", CreatedBy = 1, CreatedDate = DateTime.UtcNow }
             //);
             //            


             //            modelBuilder.Entity<DimensionTranslations>().HasData(
             //    new DimensionTranslations { Id = 1, Name = "Dimension2",  ShortText = "DT2", LongText = "Dimension Type 2", DimensionsId = 100, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DimensionTranslations { Id = 2, Name = "Dimension2", ShortText = "DT3", LongText = "Dimension Type 3", DimensionsId = 100, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DimensionTranslations {Id = 3, Name = "Dimension2", ShortText = "DT4", LongText = "Dimension Type 4", DimensionsId = 101, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DimensionTranslations {Id = 4, Name = "Dimension2", ShortText = "DT5", LongText = "Dimension Type 5", DimensionsId = 101, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
             //);
             //            modelBuilder.Entity<DimensionTypeTranslations>().HasData(
             //    new DimensionTypeTranslations { Id = 1, Name = "Dimension2", ShortText = "DT2", LongText = "Dimension Type 2", DimensionTypeId = 50, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DimensionTypeTranslations { Id = 2, Name = "Dimension2", ShortText = "DT3", LongText = "Dimension Type 3", DimensionTypeId = 50, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DimensionTypeTranslations { Id = 3, Name = "Dimension2", ShortText = "DT4", LongText = "Dimension Type 4", DimensionTypeId = 51, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow },
             //    new DimensionTypeTranslations { Id = 4, Name = "Dimension2", ShortText = "DT5", LongText = "Dimension Type 5", DimensionTypeId = 51, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow }
             //);
             //        modelBuilder.Entity<DatapointModel>().HasData(
             //    new DatapointModel
             //    {
             //        DimensionsId = 10,
             //        DatapointId = 1,
             //        DimensionsId = 100,
             //        SortingType = SortingTypeEnum.RowType
             //    },
             //    new DatapointModel
             //    {
             //        DimensionsId = 11,
             //        DatapointId = 1,
             //        DimensionsId = 101,
             //        SortingType = SortingTypeEnum.ColumType
             //    },
             //    new DatapointModel
             //    {
             //        DimensionsId = 12,
             //        DatapointId = 1,
             //        DimensionsId = 102,
             //        SortingType = SortingTypeEnum.FilterType
             //    }
             //);
             base.OnModelCreating(modelBuilder);
        }

    }
}
