// <auto-generated />
using System;
using ESG.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESG.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240813111602_migration 2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESG.Domain.Entities.Audit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currency");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CurrencyCode = "USD",
                            LongText = "United States Dollar",
                            Name = "US Dollar",
                            ShortText = "USD"
                        },
                        new
                        {
                            Id = 2L,
                            CurrencyCode = "EUR",
                            LongText = "Euro",
                            Name = "Euro",
                            ShortText = "EUR"
                        },
                        new
                        {
                            Id = 3L,
                            CurrencyCode = "INR",
                            LongText = "Indian Rupee",
                            Name = "Indian Rupee",
                            ShortText = "INR"
                        },
                        new
                        {
                            Id = 4L,
                            CurrencyCode = "GBP",
                            LongText = "British Pound Sterling",
                            Name = "British Pound",
                            ShortText = "GBP"
                        },
                        new
                        {
                            Id = 5L,
                            CurrencyCode = "CAD",
                            LongText = "Canadian Dollar",
                            Name = "Canadian Dollar",
                            ShortText = "CAD"
                        },
                        new
                        {
                            Id = 6L,
                            CurrencyCode = "AUD",
                            LongText = "Australian Dollar",
                            Name = "Australian Dollar",
                            ShortText = "AUD"
                        },
                        new
                        {
                            Id = 7L,
                            CurrencyCode = "JPY",
                            LongText = "Japanese Yen",
                            Name = "Japanese Yen",
                            ShortText = "JPY"
                        },
                        new
                        {
                            Id = 8L,
                            CurrencyCode = "CHF",
                            LongText = "Swiss Franc",
                            Name = "Swiss Franc",
                            ShortText = "CHF"
                        },
                        new
                        {
                            Id = 9L,
                            CurrencyCode = "CNY",
                            LongText = "Chinese Yuan Renminbi",
                            Name = "Chinese Yuan",
                            ShortText = "CNY"
                        },
                        new
                        {
                            Id = 10L,
                            CurrencyCode = "RUB",
                            LongText = "Russian Ruble",
                            Name = "Russian Ruble",
                            ShortText = "RUB"
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.DataPointTypes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("DataPointTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7090),
                            LanguageId = 1L,
                            LongText = "Type 1",
                            Name = "DatapointType1",
                            ShortText = "T1",
                            State = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 2L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7092),
                            LanguageId = 2L,
                            LongText = "Type 2",
                            Name = "DatapointType2",
                            ShortText = "T2",
                            State = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 3L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7094),
                            LanguageId = 3L,
                            LongText = "Type 3",
                            Name = "DatapointType3",
                            ShortText = "T3",
                            State = 1
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = 0L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7095),
                            LanguageId = 1L,
                            LongText = "Type 5",
                            Name = "DatapointType5",
                            ShortText = "T5",
                            State = 1
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = 0L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7096),
                            LanguageId = 1L,
                            LongText = "Type 6",
                            Name = "DatapointType6",
                            ShortText = "T6",
                            State = 1
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7098),
                            LanguageId = 1L,
                            LongText = "Type 7",
                            Name = "DatapointType7",
                            ShortText = "T7",
                            State = 1
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = 0L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7099),
                            LanguageId = 1L,
                            LongText = "Type 8",
                            Name = "DatapointType8",
                            ShortText = "T8",
                            State = 1
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7100),
                            LanguageId = 1L,
                            LongText = "Type 9",
                            Name = "DatapointType9",
                            ShortText = "T9",
                            State = 1
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7102),
                            LanguageId = 1L,
                            LongText = "Type 10",
                            Name = "DatapointType10",
                            ShortText = "T10",
                            State = 1
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.DataPointValues", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DatapointTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrency")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNarrative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUOM")
                        .HasColumnType("boolean");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DatapointTypeId");

                    b.HasIndex("LanguageId");

                    b.ToTable("DataPointValues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7131),
                            DatapointTypeId = 1L,
                            IsCurrency = true,
                            IsNarrative = false,
                            IsUOM = false,
                            LanguageId = 1L,
                            Name = "DataPointValue1",
                            Purpose = "Purpose 1",
                            State = 1,
                            Value = "Value 1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7133),
                            DatapointTypeId = 1L,
                            IsCurrency = false,
                            IsNarrative = false,
                            IsUOM = true,
                            LanguageId = 1L,
                            Name = "DataPointValue2",
                            Purpose = "Purpose 2",
                            State = 1,
                            Value = "Value 2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7135),
                            DatapointTypeId = 1L,
                            IsCurrency = true,
                            IsNarrative = false,
                            IsUOM = false,
                            LanguageId = 1L,
                            Name = "DataPointValue3",
                            Purpose = "Purpose 3",
                            State = 1,
                            Value = "Value 3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7137),
                            DatapointTypeId = 1L,
                            IsCurrency = false,
                            IsNarrative = true,
                            IsUOM = false,
                            LanguageId = 1L,
                            Name = "DataPointValue4",
                            Purpose = "Purpose 4",
                            State = 1,
                            Value = "Value 4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7139),
                            DatapointTypeId = 1L,
                            IsCurrency = true,
                            IsNarrative = false,
                            IsUOM = false,
                            LanguageId = 1L,
                            Name = "DataPointValue5",
                            Purpose = "Purpose 5",
                            State = 1,
                            Value = "Value 5"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7141),
                            DatapointTypeId = 1L,
                            IsCurrency = false,
                            IsNarrative = false,
                            IsUOM = true,
                            LanguageId = 1L,
                            Name = "DataPointValue6",
                            Purpose = "Purpose 6",
                            State = 1,
                            Value = "Value 6"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7143),
                            DatapointTypeId = 1L,
                            IsCurrency = true,
                            IsNarrative = false,
                            IsUOM = false,
                            LanguageId = 2L,
                            Name = "DataPointValue7",
                            Purpose = "Purpose 7",
                            State = 1,
                            Value = "Value 7"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7145),
                            DatapointTypeId = 1L,
                            IsCurrency = false,
                            IsNarrative = true,
                            IsUOM = false,
                            LanguageId = 2L,
                            Name = "DataPointValue8",
                            Purpose = "Purpose 8",
                            State = 1,
                            Value = "Value 8"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7146),
                            DatapointTypeId = 1L,
                            IsCurrency = true,
                            IsNarrative = false,
                            IsUOM = false,
                            LanguageId = 2L,
                            Name = "DataPointValue9",
                            Purpose = "Purpose 9",
                            State = 1,
                            Value = "Value 9"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7149),
                            DatapointTypeId = 1L,
                            IsCurrency = false,
                            IsNarrative = false,
                            IsUOM = true,
                            LanguageId = 2L,
                            Name = "DataPointValue10",
                            Purpose = "Purpose 10",
                            State = 1,
                            Value = "Value 10"
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.DatapointModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DatapointId")
                        .HasColumnType("bigint");

                    b.Property<long>("DimentionsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortingType")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DatapointId");

                    b.HasIndex("DimentionsId");

                    b.ToTable("DatapointModel");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionTranslations", b =>
                {
                    b.Property<long>("DimentionsId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("LanguageId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("DimentionsId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageId1");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("DimensionTranslations");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHeirarchialDimension")
                        .HasColumnType("boolean");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortText")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("DimensionTypes");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionTypeTranslations", b =>
                {
                    b.Property<long>("DimensionTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("LanguageId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("DimensionTypeId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageId1");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("DimensionTypeTranslations");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Dimensions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DimensionTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsHeirarchialDimension")
                        .HasColumnType("boolean");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DimensionTypeId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsoCode = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 2L,
                            IsoCode = "uk",
                            Name = "Ukrainian"
                        },
                        new
                        {
                            Id = 3L,
                            IsoCode = "be",
                            Name = "Belarusian"
                        },
                        new
                        {
                            Id = 4L,
                            IsoCode = "et",
                            Name = "Estonian"
                        },
                        new
                        {
                            Id = 5L,
                            IsoCode = "lv",
                            Name = "Latvian"
                        },
                        new
                        {
                            Id = 6L,
                            IsoCode = "lt",
                            Name = "Lithuanian"
                        },
                        new
                        {
                            Id = 7L,
                            IsoCode = "ka",
                            Name = "Georgian"
                        },
                        new
                        {
                            Id = 8L,
                            IsoCode = "hy",
                            Name = "Armenian"
                        },
                        new
                        {
                            Id = 9L,
                            IsoCode = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            Id = 10L,
                            IsoCode = "kk",
                            Name = "Kazakh"
                        },
                        new
                        {
                            Id = 11L,
                            IsoCode = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            Id = 12L,
                            IsoCode = "tk",
                            Name = "Turkmen"
                        },
                        new
                        {
                            Id = 13L,
                            IsoCode = "tg",
                            Name = "Tajik"
                        },
                        new
                        {
                            Id = 14L,
                            IsoCode = "ky",
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            Id = 15L,
                            IsoCode = "mo",
                            Name = "Moldovan"
                        },
                        new
                        {
                            Id = 16L,
                            IsoCode = "tt",
                            Name = "Tatar"
                        },
                        new
                        {
                            Id = 17L,
                            IsoCode = "ba",
                            Name = "Bashkir"
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatsName")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("text");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TenantId");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Country = "USA",
                            CreatedBy = 0L,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@org1.com",
                            FirstName = "John",
                            LanguageId = 1L,
                            LatsName = "Doe",
                            Name = "ESG Global",
                            PostalCode = "12345",
                            RegistrationId = "REG-001",
                            State = 1,
                            StreetAddress = "123 Main St",
                            StreetNumber = "456",
                            TenantId = 1L
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.OrganizationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6762),
                            OrganizationId = 1L,
                            State = 1,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6765),
                            OrganizationId = 1L,
                            State = 1,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6766),
                            OrganizationId = 1L,
                            State = 1,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "AdminEE"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "ClientAdmin"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "ESG Global"
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("UnitOfMeasureTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UnitOfMeasureTypeId");

                    b.ToTable("UnitOfMeasures");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            Code = "weight",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6944),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6944),
                            LongText = "Kilogram",
                            Name = "weight",
                            OrganizationId = 1L,
                            ShortText = "kg",
                            State = 1,
                            UnitOfMeasureTypeId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Code = "weight",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6948),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6948),
                            LongText = "Gram",
                            Name = "weight",
                            OrganizationId = 1L,
                            ShortText = "gm",
                            State = 1,
                            UnitOfMeasureTypeId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Code = "weight",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6951),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6951),
                            LongText = "milliliter",
                            Name = "amount",
                            OrganizationId = 1L,
                            ShortText = "ml",
                            State = 1,
                            UnitOfMeasureTypeId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Code = "weight",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6953),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6954),
                            LongText = "meterpersecond",
                            Name = "speed",
                            OrganizationId = 1L,
                            ShortText = "m/s",
                            State = 1,
                            UnitOfMeasureTypeId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Code = "weight",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6956),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6957),
                            LongText = "kmperhour",
                            Name = "speed",
                            OrganizationId = 1L,
                            ShortText = "kmph",
                            State = 1,
                            UnitOfMeasureTypeId = 1L
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureTranslations", b =>
                {
                    b.Property<long>("UnitOfMeasureId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("LanguageId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("UnitOfMeasureId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageId1");

                    b.ToTable("UnitOfMeasureTranslations");

                    b.HasData(
                        new
                        {
                            UnitOfMeasureId = 4L,
                            LanguageId = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6994),
                            Id = 10L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6994),
                            LongText = "Kilogram",
                            Name = "weight",
                            ShortText = "kg",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureId = 4L,
                            LanguageId = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6997),
                            Id = 11L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6997),
                            LongText = "Gram",
                            Name = "weight",
                            ShortText = "gm",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureId = 6L,
                            LanguageId = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7011),
                            Id = 12L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7012),
                            LongText = "milliliter",
                            Name = "amount",
                            ShortText = "ml",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureId = 7L,
                            LanguageId = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7014),
                            Id = 13L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7014),
                            LongText = "meterpersecond",
                            Name = "speed",
                            ShortText = "m/s",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureId = 7L,
                            LanguageId = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7016),
                            Id = 14L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7017),
                            LongText = "kmperhour",
                            Name = "speed",
                            ShortText = "kmph",
                            State = 0
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("UnitOfMeasureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "speed",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6844),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6845),
                            LongText = "Type 1",
                            Name = "Speed",
                            OrganizationId = 1L,
                            ShortText = "T1",
                            State = 1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "weight",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6907),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6908),
                            LongText = "Type 2",
                            Name = "Weight",
                            OrganizationId = 1L,
                            ShortText = "T2",
                            State = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "amount",
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6911),
                            LanguageId = 1L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6912),
                            LongText = "Type 3",
                            Name = "Amount",
                            OrganizationId = 1L,
                            ShortText = "T3",
                            State = 1
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureTypeTranslations", b =>
                {
                    b.Property<long>("UnitOfMeasureTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("LanguageId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("UnitOfMeasureTypeId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageId1");

                    b.ToTable("UnitOfMeasureTypeTranslations");

                    b.HasData(
                        new
                        {
                            UnitOfMeasureTypeId = 2L,
                            LanguageId = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7044),
                            Id = 10L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7045),
                            LongText = "Kilogram",
                            Name = "weight",
                            ShortText = "kg",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureTypeId = 2L,
                            LanguageId = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7047),
                            Id = 11L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7047),
                            LongText = "Gram",
                            Name = "weight",
                            ShortText = "gm",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureTypeId = 3L,
                            LanguageId = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7049),
                            Id = 12L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7050),
                            LongText = "milliliter",
                            Name = "amount",
                            ShortText = "ml",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureTypeId = 1L,
                            LanguageId = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7051),
                            Id = 13L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7052),
                            LongText = "meterpersecond",
                            Name = "speed",
                            ShortText = "m/s",
                            State = 0
                        },
                        new
                        {
                            UnitOfMeasureTypeId = 1L,
                            LanguageId = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7054),
                            Id = 14L,
                            LastModifiedBy = 1L,
                            LastModifiedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(7054),
                            LongText = "kmperhour",
                            Name = "speed",
                            ShortText = "kmph",
                            State = 0
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("OrganizationUserId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OrganizationUserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6436),
                            Email = "user1@example.com",
                            FirstName = "John",
                            LanguageId = 1L,
                            LastName = "Doe",
                            Password = new byte[] { 112, 97, 115, 115, 119, 111, 114, 100, 49 },
                            PhoneNumber = "1234567890",
                            SecurityStamp = new Guid("bfacb544-44fe-4c9b-a150-358eacea4005"),
                            State = 1
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6471),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            LanguageId = 1L,
                            LastName = "Smith",
                            Password = new byte[] { 112, 97, 115, 115, 119, 111, 114, 100, 50 },
                            PhoneNumber = "0987654321",
                            SecurityStamp = new Guid("1f813481-2f0d-4f0f-b341-ea349b48f61a"),
                            State = 1
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6475),
                            Email = "user3@example.com",
                            FirstName = "Alice",
                            LanguageId = 1L,
                            LastName = "Johnson",
                            Password = new byte[] { 112, 97, 115, 115, 119, 111, 114, 100, 51 },
                            PhoneNumber = "2345678901",
                            SecurityStamp = new Guid("15997e7c-76cf-4821-be79-492d6064a30a"),
                            State = 1
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6809),
                            RoleId = 1L,
                            State = 1,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6810),
                            RoleId = 2L,
                            State = 1,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedBy = 1L,
                            CreatedDate = new DateTime(2024, 8, 13, 11, 16, 2, 244, DateTimeKind.Utc).AddTicks(6811),
                            RoleId = 3L,
                            State = 1,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("ESG.Domain.Entities.DataPointTypes", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DataPointValues", b =>
                {
                    b.HasOne("ESG.Domain.Entities.DataPointTypes", "DataPointType")
                        .WithMany("DataPointValues")
                        .HasForeignKey("DatapointTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataPointType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DatapointModel", b =>
                {
                    b.HasOne("ESG.Domain.Entities.DataPointTypes", "DataPointTypes")
                        .WithMany("DatapointModels")
                        .HasForeignKey("DatapointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Dimensions", "Dimentions")
                        .WithMany("DatapointModels")
                        .HasForeignKey("DimentionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataPointTypes");

                    b.Navigation("Dimentions");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionTranslations", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Dimensions", "Dimensions")
                        .WithMany("DimensionTranslations")
                        .HasForeignKey("DimentionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", null)
                        .WithMany("DimensionTranslations")
                        .HasForeignKey("LanguageId1");

                    b.HasOne("ESG.Domain.Entities.Organization", "Organization")
                        .WithOne("DimensionTranslations")
                        .HasForeignKey("ESG.Domain.Entities.DimensionTranslations", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensions");

                    b.Navigation("Language");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionType", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany("DimensionTypes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Organization", "Organization")
                        .WithOne("DimensionType")
                        .HasForeignKey("ESG.Domain.Entities.DimensionType", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionTypeTranslations", b =>
                {
                    b.HasOne("ESG.Domain.Entities.DimensionType", "DimensionType")
                        .WithMany("DimensionTranslations")
                        .HasForeignKey("DimensionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", null)
                        .WithMany("DimensionTypeTranslations")
                        .HasForeignKey("LanguageId1");

                    b.HasOne("ESG.Domain.Entities.Organization", "Organization")
                        .WithOne("DimensionTypeTranslations")
                        .HasForeignKey("ESG.Domain.Entities.DimensionTypeTranslations", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionType");

                    b.Navigation("Language");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Dimensions", b =>
                {
                    b.HasOne("ESG.Domain.Entities.DimensionType", "DimensionType")
                        .WithMany("Dimensions")
                        .HasForeignKey("DimensionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany("Dimensions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Organization", "Organization")
                        .WithOne("Dimensions")
                        .HasForeignKey("ESG.Domain.Entities.Dimensions", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionType");

                    b.Navigation("Language");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Organization", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Languages")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Organizations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Languages");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ESG.Domain.Entities.OrganizationUser", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Organization", "Organizations")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany("UnitOfMeasures")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.UnitOfMeasureType", "UnitOfMeasureTypes")
                        .WithMany("UnitOfMeasure")
                        .HasForeignKey("UnitOfMeasureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Organization");

                    b.Navigation("UnitOfMeasureTypes");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureTranslations", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", null)
                        .WithMany("UnitOfMeasureTranslations")
                        .HasForeignKey("LanguageId1");

                    b.HasOne("ESG.Domain.Entities.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("UnitOfMeasureTranslations")
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureType", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany("UnitOfMeasureTypes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureTypeTranslations", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.Language", null)
                        .WithMany("UnitOfMeasureTypeTranslations")
                        .HasForeignKey("LanguageId1");

                    b.HasOne("ESG.Domain.Entities.UnitOfMeasureType", "UnitOfMeasureType")
                        .WithMany("UnitOfMeasureTypeTranslations")
                        .HasForeignKey("UnitOfMeasureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("UnitOfMeasureType");
                });

            modelBuilder.Entity("ESG.Domain.Entities.User", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Language", "Languages")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.OrganizationUser", null)
                        .WithMany("Users")
                        .HasForeignKey("OrganizationUserId");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ESG.Domain.Entities.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESG.Domain.Entities.User", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DataPointTypes", b =>
                {
                    b.Navigation("DataPointValues");

                    b.Navigation("DatapointModels");
                });

            modelBuilder.Entity("ESG.Domain.Entities.DimensionType", b =>
                {
                    b.Navigation("DimensionTranslations");

                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Dimensions", b =>
                {
                    b.Navigation("DatapointModels");

                    b.Navigation("DimensionTranslations");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Language", b =>
                {
                    b.Navigation("DimensionTranslations");

                    b.Navigation("DimensionTypeTranslations");

                    b.Navigation("DimensionTypes");

                    b.Navigation("Dimensions");

                    b.Navigation("UnitOfMeasureTranslations");

                    b.Navigation("UnitOfMeasureTypeTranslations");

                    b.Navigation("UnitOfMeasureTypes");

                    b.Navigation("UnitOfMeasures");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Organization", b =>
                {
                    b.Navigation("DimensionTranslations")
                        .IsRequired();

                    b.Navigation("DimensionType")
                        .IsRequired();

                    b.Navigation("DimensionTypeTranslations")
                        .IsRequired();

                    b.Navigation("Dimensions")
                        .IsRequired();
                });

            modelBuilder.Entity("ESG.Domain.Entities.OrganizationUser", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ESG.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("UnitOfMeasureTranslations");
                });

            modelBuilder.Entity("ESG.Domain.Entities.UnitOfMeasureType", b =>
                {
                    b.Navigation("UnitOfMeasure");

                    b.Navigation("UnitOfMeasureTypeTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
