using ESG.Domain.Models;
using ESG.Domain.Enum;
using Microsoft.EntityFrameworkCore;
using System;

namespace ESG.Infrastructure.Persistence.DataBaseSeeder
{
    public static class DimensionSeed
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DimensionType>().HasData(
                new DimensionType { Id = 1, Code = "yyyy", ShortText = "Year", LongText = "Year", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 2, Code = "m", ShortText = "Month", LongText = "Month", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 3, Code = "q", ShortText = "Quarter", LongText = "Quarter", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 4, Code = "d", ShortText = "Day", LongText = "Day", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 5, Code = "vatyp", ShortText = "Value Type", LongText = "Value Type", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 6, Code = "cntry", ShortText = "Country", LongText = "Country", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 7, Code = "city", ShortText = "City", LongText = "City", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 8, Code = "rgn", ShortText = "Region", LongText = "Region", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 9, Code = "sdg", ShortText = "SDG", LongText = "Sustainable Development", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 10, Code = "liro", ShortText = "Line Of Reporting", LongText = "Line Of Reporting", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 11, Code = "domn", ShortText = "Domain", LongText = "Domain", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 12, Code = "bsnss", ShortText = "Business", LongText = "Business", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 13, Code = "mrkt", ShortText = "Market", LongText = "Market", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionType { Id = 14, Code = "factory", ShortText = "Factory", LongText = "Factory", State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }

                );
            modelBuilder.Entity<DimensionTypeTranslation>().HasData(
                 new DimensionTypeTranslation { Id = 1, DimensionTypeId = 1, LanguageId = 2, ShortText = "Jaar", LongText = "Jaar", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 2, DimensionTypeId = 2, LanguageId = 2, ShortText = "Maand", LongText = "Maand", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 3, DimensionTypeId = 3, LanguageId = 2, ShortText = "Kwartaal", LongText = "Kwartaal", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 4, DimensionTypeId = 4, LanguageId = 2, ShortText = "Dag", LongText = "Dag", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 5, DimensionTypeId = 5, LanguageId = 2, ShortText = "Waardetype", LongText = "Waardetype", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 6, DimensionTypeId = 6, LanguageId = 2, ShortText = "Land", LongText = "Land", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 7, DimensionTypeId = 7, LanguageId = 2, ShortText = "Stad", LongText = "Stad", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 8, DimensionTypeId = 8, LanguageId = 2, ShortText = "Regio", LongText = "Regio", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 9, DimensionTypeId = 9, LanguageId = 2, ShortText = "SDG", LongText = "Duurzame Ontwikkeling", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 10, DimensionTypeId = 10, LanguageId = 2, ShortText = "Rapporteringslijn", LongText = "Rapporteringslijn", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 11, DimensionTypeId = 11, LanguageId = 2, ShortText = "Domein", LongText = "Domein", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 12, DimensionTypeId = 12, LanguageId = 2, ShortText = "Bedrijf", LongText = "Bedrijf", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 13, DimensionTypeId = 13, LanguageId = 2, ShortText = "Markt", LongText = "Markt", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                 new DimensionTypeTranslation { Id = 14, DimensionTypeId = 14, LanguageId = 2, ShortText = "Fabriek", LongText = "Fabriek", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }
             );


            modelBuilder.Entity<Dimension>().HasData(
                new Dimension { Id = 1000, Code = "act", ShortText = "Actual", LongText = "Actual", DimensionTypeId = 5, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1001, Code = "base", ShortText = "Baseline", LongText = "Baseline", DimensionTypeId = 5, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1002, Code = "target", ShortText = "Target", LongText = "Target", DimensionTypeId = 5, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1003, Code = "de", ShortText = "DE", LongText = "Germany", DimensionTypeId = 6, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1004, Code = "nl", ShortText = "NL", LongText = "The Netherlands", DimensionTypeId = 6, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1005, Code = "dap", ShortText = "DAP", LongText = "Domestic Appliances", DimensionTypeId = 12, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1006, Code = "pms", ShortText = "PMS", LongText = "Medical systems", DimensionTypeId = 12, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1007, Code = "eur", ShortText = "EUR", LongText = "Europe", DimensionTypeId = 13, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1008, Code = "ame", ShortText = "AME", LongText = "Africa, Middle East", DimensionTypeId = 13, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1009, Code = "tern", ShortText = "Terneuzen", LongText = "Terneuzen", DimensionTypeId = 14, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1010, Code = "2023", ShortText = "2023", LongText = "2023", DimensionTypeId = 1, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1011, Code = "2024", ShortText = "2024", LongText = "2024", DimensionTypeId = 1, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1012, Code = "2025", ShortText = "2025", LongText = "2025", DimensionTypeId = 1, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1013, Code = "Jan", ShortText = "January", LongText = "January", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1014, Code = "Feb", ShortText = "February", LongText = "February", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1015, Code = "Mar", ShortText = "March", LongText = "March", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1016, Code = "Apr", ShortText = "April", LongText = "April", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1017, Code = "May", ShortText = "May", LongText = "May", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1018, Code = "Jun", ShortText = "June", LongText = "June", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1019, Code = "Jul", ShortText = "July", LongText = "July", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1020, Code = "Aug", ShortText = "August", LongText = "August", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1021, Code = "Sep", ShortText = "September", LongText = "September", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1022, Code = "Oct", ShortText = "October", LongText = "October", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1023, Code = "Nov", ShortText = "November", LongText = "November", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Dimension { Id = 1024, Code = "Dec", ShortText = "December", LongText = "December", DimensionTypeId = 2, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }
                //new Dimension { Id = 1025, Code = "Q1", ShortText = "1st quarter", LongText = "1- quarter", DimensionTypeId = 3, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                //new Dimension { Id = 1026, Code = "Q2", ShortText = "2nd quarter", LongText = "2- quarter", DimensionTypeId = 3, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                //new Dimension { Id = 1027, Code = "Q3", ShortText = "3rd quarter", LongText = "3- quarter", DimensionTypeId = 3, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                //new Dimension { Id = 1028, Code = "Q4", ShortText = "4th quarter", LongText = "4- quarter", DimensionTypeId = 3, State = StateEnum.active, OrganizationId = 1, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }

            );
            modelBuilder.Entity<DimensionTranslation>().HasData(
                new DimensionTranslation { Id = 1, DimensionsId = 1000, LanguageId = 2, ShortText = "Aktuell", LongText = "Aktuell", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 2, DimensionsId = 1001, LanguageId = 2, ShortText = "Basislinie", LongText = "Basislinie", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 3, DimensionsId = 1002, LanguageId = 2, ShortText = "Ziel", LongText = "Ziel", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 4, DimensionsId = 1003, LanguageId = 2, ShortText = "DE", LongText = "Deutschland", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 5, DimensionsId = 1004, LanguageId = 2, ShortText = "NL", LongText = "Niederlande", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 6, DimensionsId = 1005, LanguageId = 2, ShortText = "DAP", LongText = "Haushaltsgeräte", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 7, DimensionsId = 1006, LanguageId = 2, ShortText = "PMS", LongText = "Medizinische Systeme", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 8, DimensionsId = 1007, LanguageId = 2, ShortText = "EUR", LongText = "Europa", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 9, DimensionsId = 1008, LanguageId = 2, ShortText = "AME", LongText = "Afrika, Naher Osten", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 10, DimensionsId = 1009, LanguageId = 2, ShortText = "Terneuzen", LongText = "Terneuzen", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 11, DimensionsId = 1010, LanguageId = 2, ShortText = "2023", LongText = "2023", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 12, DimensionsId = 1011, LanguageId = 2, ShortText = "2024", LongText = "2024", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 13, DimensionsId = 1012, LanguageId = 2, ShortText = "2025", LongText = "2025", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 14, DimensionsId = 1013, LanguageId = 2, ShortText = "Januar", LongText = "Januar", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 15, DimensionsId = 1014, LanguageId = 2, ShortText = "Februar", LongText = "Februar", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 16, DimensionsId = 1015, LanguageId = 2, ShortText = "März", LongText = "März", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 17, DimensionsId = 1016, LanguageId = 2, ShortText = "April", LongText = "April", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 18, DimensionsId = 1017, LanguageId = 2, ShortText = "Mai", LongText = "Mai", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 19, DimensionsId = 1018, LanguageId = 2, ShortText = "Juni", LongText = "Juni", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 20, DimensionsId = 1019, LanguageId = 2, ShortText = "Juli", LongText = "Juli", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 21, DimensionsId = 1020, LanguageId = 2, ShortText = "August", LongText = "August", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 22, DimensionsId = 1021, LanguageId = 2, ShortText = "September", LongText = "September", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 23, DimensionsId = 1022, LanguageId = 2, ShortText = "Oktober", LongText = "Oktober", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 24, DimensionsId = 1023, LanguageId = 2, ShortText = "November", LongText = "November", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new DimensionTranslation { Id = 25, DimensionsId = 1024, LanguageId = 2, ShortText = "Dezember", LongText = "Dezember", State = StateEnum.active, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }
            );

        }
    }
}
