using ESG.Domain.Models;
using ESG.Domain.Enum;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ESG.Infrastructure.Persistence.DataBaseSeeder
{
    public class StandardSeed
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Standard>().HasData(
                // English Entries (LanguageId = 1)
                new Standard { Id = 1, Code = "ESRS2_GP", ShortText = "ESRS2_GP - General principles", LongText = "ESRS2_GP - General principles", State = StateEnum.active, LanguageId = 1, TopicId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 2, Code = "ESRS2_MDR", ShortText = "ESRS2_MDR - General disclosures", LongText = "ESRS2_MDR - General disclosures", State = StateEnum.active, LanguageId = 1, TopicId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 3, Code = "E1", ShortText = "E1 - Climate change", LongText = "E1 - Climate change", State = StateEnum.active, LanguageId = 1, TopicId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 4, Code = "E2", ShortText = "E2 - Pollution", LongText = "E2 - Pollution", State = StateEnum.active, LanguageId = 1, TopicId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 5, Code = "E3", ShortText = "E3 - Water and marine resources", LongText = "E3 - Water and marine resources", State = StateEnum.active, LanguageId = 1, TopicId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 6, Code = "E4", ShortText = "E4 - Biodiversity and ecosystems", LongText = "E4 - Biodiversity and ecosystems", State = StateEnum.active, LanguageId = 1, TopicId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 7, Code = "E5", ShortText = "E5 - Resource use and circular economy", LongText = "E5 - Resource use and circular economy", State = StateEnum.active, LanguageId = 1, TopicId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 8, Code = "S1", ShortText = "S1 - Own workforce", LongText = "S1 - Own workforce", State = StateEnum.active, LanguageId = 1, TopicId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 9, Code = "S2", ShortText = "S2 - Workers in the value chain", LongText = "S2 - Workers in the value chain", State = StateEnum.active, LanguageId = 1, TopicId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 10, Code = "S3", ShortText = "S3 - Affected communities", LongText = "S3 - Affected communities", State = StateEnum.active, LanguageId = 1, TopicId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 11, Code = "S4", ShortText = "S4 - Consumers and end-users", LongText = "S4 - Consumers and end-users", State = StateEnum.active, LanguageId = 1, TopicId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 12, Code = "G1", ShortText = "G1 - Governance, risk, and internal control", LongText = "G1 - Governance, risk, and internal control", State = StateEnum.active, LanguageId = 1, TopicId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 13, Code = "B", ShortText = "VSME Basic", LongText = "VSME Basic", State = StateEnum.active, LanguageId = 1, TopicId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new Standard { Id = 14, Code = "C", ShortText = "VSME Comprehensive", LongText = "VSME Comprehensive", State = StateEnum.active, LanguageId = 1, TopicId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }
             );            
            modelBuilder.Entity<StandardTranslation>().HasData(
                new StandardTranslation { Id = 1, StandardId = 1, ShortText = "ESRS2_GP - General principles", LongText = "ESRS2_GP - General principles", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 2, StandardId = 2, ShortText = "ESRS2_MDR - General disclosures", LongText = "ESRS2_MDR - General disclosures", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 3, StandardId = 3, ShortText = "E1 - Climate change", LongText = "E1 - Climate change", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 4, StandardId = 4, ShortText = "E2 - Pollution", LongText = "E2 - Pollution", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 5, StandardId = 5, ShortText = "E3 - Water & marine resources", LongText = "E3 - Water & marine resources", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 6, StandardId = 6, ShortText = "E4 - Biodiversity and eco systems", LongText = "E4 - Biodiversity and eco systems", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 7, StandardId = 7, ShortText = "E5 - Resourtce use and circular economy", LongText = "E5 - Resourtce use and circular economy", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 8, StandardId = 8, ShortText = "S1 - Own workforce", LongText = "S1 - Own workforce", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 9, StandardId = 9, ShortText = "S2 - Workers in value chain", LongText = "S2 - Workers in value chain", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 10, StandardId = 10, ShortText = "S3 - Affected communities", LongText = "S3 - Affected communities", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 11, StandardId = 11, ShortText = "S4 - Consumers and end-users", LongText = "S4 - Consumers and end-users", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 12, StandardId = 12, ShortText = "G1 - Business Conduct", LongText = "G1 - Business Conduct", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 13, StandardId = 13, ShortText = "VSME Basic", LongText = "VSME Basic", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 14, StandardId = 14, ShortText = "VSME Comprehensive", LongText = "VSME Comprehensive", State = StateEnum.active, LanguageId = 1, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 15, StandardId = 1, ShortText = "ESRS2_GP - Principes généraux", LongText = "ESRS2_GP - Principes généraux", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 16, StandardId = 2, ShortText = "ESRS2_MDR - Informations générales", LongText = "ESRS2_MDR - Informations générales", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 17, StandardId = 3, ShortText = "E1 - Changement climatique", LongText = "E1 - Changement climatique", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 18, StandardId = 4, ShortText = "E2 - Pollution", LongText = "E2 - Pollution", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 19, StandardId = 5, ShortText = "E3 - Ressources en eau et marines", LongText = "E3 - Ressources en eau et marines", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 20, StandardId = 6, ShortText = "E4 - Biodiversité et écosystèmes", LongText = "E4 - Biodiversité et écosystèmes", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 21, StandardId = 7, ShortText = "E5 - Utilisation des ressources et économie circulaire", LongText = "E5 - Utilisation des ressources et économie circulaire", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 22, StandardId = 8, ShortText = "S1 - Main-d'œuvre propre", LongText = "S1 - Main-d'œuvre propre", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 23, StandardId = 9, ShortText = "S2 - Travailleurs dans la chaîne de valeur", LongText = "S2 - Travailleurs dans la chaîne de valeur", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 24, StandardId = 10, ShortText = "S3 - Communautés affectées", LongText = "S3 - Communautés affectées", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 25, StandardId = 11, ShortText = "S4 - Consommateurs et utilisateurs finaux", LongText = "S4 - Consommateurs et utilisateurs finaux", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 26, StandardId = 12, ShortText = "G1 - Conduite des affaires", LongText = "G1 - Conduite des affaires", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 27, StandardId = 13, ShortText = "VSME Basic", LongText = "VSME Basic", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 28, StandardId = 14, ShortText = "VSME Comprehensive", LongText = "VSME Comprehensive", State = StateEnum.active, LanguageId = 4, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 29, StandardId = 1, ShortText = "ESRS2_GP - Allgemeine Grundsätze", LongText = "ESRS2_GP - Allgemeine Grundsätze", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 30, StandardId = 2, ShortText = "ESRS2_MDR - Allgemeine Angaben", LongText = "ESRS2_MDR - Allgemeine Angaben", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 31, StandardId = 3, ShortText = "E1 - Klimawandel", LongText = "E1 - Klimawandel", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 32, StandardId = 4, ShortText = "E2 - Umweltverschmutzung", LongText = "E2 - Umweltverschmutzung", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 33, StandardId = 5, ShortText = "E3 - Wasser- und Meeresressourcen", LongText = "E3 - Wasser- und Meeresressourcen", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 34, StandardId = 6, ShortText = "E4 - Biodiversität und Ökosysteme", LongText = "E4 - Biodiversität und Ökosysteme", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 35, StandardId = 7, ShortText = "E5 - Ressourcennutzung und Kreislaufwirtschaft", LongText = "E5 - Ressourcennutzung und Kreislaufwirtschaft", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 36, StandardId = 8, ShortText = "S1 - Eigene Belegschaft", LongText = "S1 - Eigene Belegschaft", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 37, StandardId = 9, ShortText = "S2 - Arbeitnehmer in der Wertschöpfungskette", LongText = "S2 - Arbeitnehmer in der Wertschöpfungskette", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 38, StandardId = 10, ShortText = "S3 - Betroffene Gemeinden", LongText = "S3 - Betroffene Gemeinden", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 39, StandardId = 11, ShortText = "S4 - Verbraucher und Endnutzer", LongText = "S4 - Verbraucher und Endnutzer", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 40, StandardId = 12, ShortText = "G1 - Geschäftsverhalten", LongText = "G1 - Geschäftsverhalten", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 41, StandardId = 13, ShortText = "VSME Basic", LongText = "VSME Basic", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 42, StandardId = 14, ShortText = "VSME Comprehensive", LongText = "VSME Comprehensive", State = StateEnum.active, LanguageId = 5, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 43, StandardId = 1, ShortText = "ESRS2_GP - Principios generales", LongText = "ESRS2_GP - Principios generales", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 44, StandardId = 2, ShortText = "ESRS2_MDR - Información general", LongText = "ESRS2_MDR - Información general", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 45, StandardId = 3, ShortText = "E1 - Cambio climático", LongText = "E1 - Cambio climático", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 46, StandardId = 4, ShortText = "E2 - Contaminación", LongText = "E2 - Contaminación", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 47, StandardId = 5, ShortText = "E3 - Recursos hídricos y marinos", LongText = "E3 - Recursos hídricos y marinos", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 48, StandardId = 6, ShortText = "E4 - Biodiversidad y ecosistemas", LongText = "E4 - Biodiversidad y ecosistemas", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 49, StandardId = 7, ShortText = "E5 - Uso de recursos y economía circular", LongText = "E5 - Uso de recursos y economía circular", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 50, StandardId = 8, ShortText = "S1 - Trabajadores propios", LongText = "S1 - Trabajadores propios", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 51, StandardId = 9, ShortText = "S2 - Trabajadores en la cadena de valor", LongText = "S2 - Trabajadores en la cadena de valor", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 52, StandardId = 10, ShortText = "S3 - Comunidades afectadas", LongText = "S3 - Comunidades afectadas", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 53, StandardId = 11, ShortText = "S4 - Consumidores y usuarios finales", LongText = "S4 - Consumidores y usuarios finales", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 54, StandardId = 12, ShortText = "G1 - Conducta empresarial", LongText = "G1 - Conducta empresarial", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 55, StandardId = 13, ShortText = "VSME Basic", LongText = "VSME Basic", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 56, StandardId = 14, ShortText = "VSME Comprehensive", LongText = "VSME Comprehensive", State = StateEnum.active, LanguageId = 3, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 57, StandardId = 1, ShortText = "ESRS2_GP - Algemene principes", LongText = "ESRS2_GP - Algemene principes", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 58, StandardId = 2, ShortText = "ESRS2_MDR - Algemene bekendmakingen", LongText = "ESRS2_MDR - Algemene bekendmakingen", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 59, StandardId = 3, ShortText = "E1 - Klimaatverandering", LongText = "E1 - Klimaatverandering", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 60, StandardId = 4, ShortText = "E2 - Verontreiniging", LongText = "E2 - Verontreiniging", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 61, StandardId = 5, ShortText = "E3 - Water- en mariene hulpbronnen", LongText = "E3 - Water- en mariene hulpbronnen", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 62, StandardId = 6, ShortText = "E4 - Biodiversiteit en ecosystemen", LongText = "E4 - Biodiversiteit en ecosystemen", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 63, StandardId = 7, ShortText = "E5 - Hulpbronnengebruik en circulaire economie", LongText = "E5 - Hulpbronnengebruik en circulaire economie", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 64, StandardId = 8, ShortText = "S1 - Eigen personeelsbestand", LongText = "S1 - Eigen personeelsbestand", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 65, StandardId = 9, ShortText = "S2 - Werknemers in de waardeketen", LongText = "S2 - Werknemers in de waardeketen", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 66, StandardId = 10, ShortText = "S3 - Getroffen gemeenschappen", LongText = "S3 - Getroffen gemeenschappen", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 67, StandardId = 11, ShortText = "S4 - Consumenten en eindgebruikers", LongText = "S4 - Consumenten en eindgebruikers", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 68, StandardId = 12, ShortText = "G1 - Zakelijk gedrag", LongText = "G1 - Zakelijk gedrag", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 69, StandardId = 13, ShortText = "VSME Basic", LongText = "VSME Basic", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow },
                new StandardTranslation { Id = 70, StandardId = 14, ShortText = "VSME Comprehensive", LongText = "VSME Comprehensive", State = StateEnum.active, LanguageId = 2, CreatedBy = 1, CreatedDate = DateTime.UtcNow, LastModifiedBy = 1, LastModifiedDate = DateTime.UtcNow }


    );
        }
    }
}
